# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 21 Mar 2019 12:29:23 +0000
*	@ALL	1
*	@user	8
condorcet-sp:*	mhgatto	8
condorcet:*	mhgatto	1
condorcet:*	aalbespy	1
condorcet-sp:*	aalbespy	8
condorcet-sp:*	fmouillot	1
