<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jchiavassa
 * Date: Thu, 28 Mar 2019 16:41:37 +0100
 */

$conf['title'] = 'Alma - GED - Campus Condorcet';
$conf['lang'] = 'fr';
$conf['sidebar'] = 'Table des matières';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'usercc';
$conf['proxy']['pass'] = '<b>bTB0ZGVwYXNzZTs=';
$conf['plugin']['ckgedit']['scayt_lang'] = 'French/fr_FR';
$conf['plugin']['denyactions']['denyactions'] = 'media,revisions,diff,backlink,recent';
$conf['plugin']['toolbuttondel']['links'] = 'media';

// end auto-generated content
