<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jchiavassa
 * Date: Tue, 21 May 2019 10:12:55 +0200
 */

$conf['title'] = '<h3>Documentation professionnelle GED</h3>';
$conf['lang'] = 'fr';
$conf['sidebar'] = 'Table des matières';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'usercc';
$conf['proxy']['pass'] = '<b>bTB0ZGVwYXNzZTs=';
$conf['plugin']['ckgedit']['scayt_lang'] = 'French/fr_FR';
$conf['plugin']['denyactions']['denyactions'] = 'media,revisions,diff,backlink,recent';
$conf['tpl']['bootstrap3']['fluidContainer'] = '1';
$conf['tpl']['bootstrap3']['fluidContainerBtn'] = '1';
$conf['tpl']['bootstrap3']['tocLayout'] = 'navbar';
$conf['plugin']['toolbuttondel']['links'] = 'media';

// end auto-generated content
